name: create clash rule providers

on:
  push:
    branches:
      - master  # Set a branch to deploy
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: create rule providers
        run: |
          git checkout master
          rm -rf Clash/Providers/Ruleset
          cp -rf Clash/Ruleset Clash/Providers/Ruleset
          cd Clash/Providers/Ruleset
          sed -i "/,/ s/^/  - /" $ls
          sed -i "1i\payload:" $ls
          sed -i "/#/ s/^/  /" $ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
