### 通过 Github action， 在仓库的每一次 commit 后自动同步到 Gitee 上
name: sync2gitee
on:
  push:
    branches:
      - gh-pages
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Repo to CODING
      env:
          # 在 GitHub Settings->Secrets 配置 CODING_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.CODING_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "git@github.com:yangchuansheng/ACL4SSR.git"
          # 注意替换为你的 CODING 目标仓库地址
          coding-repo: "git@e.coding.net:ryanyang/ryanyang/ACL4SSR.git"
